spring:
  application:
    name: gpt-hub

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: true
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          generate_statistics: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


logging.level:
  root: INFO
  org.hibernate.SQL: debug
  org.springframework.transaction.interceptor: TRACE

server:
  servlet:
    session:
      timeout: 30m